name: C/C++ CI

on:
  push:
    branches: ["*"]

jobs:
  c-linter:
    name: c-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: c-linter
        uses: ArtificialAmateur/cpp-linter-action@master
  c-cpp-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup C/C++
        uses: aminya/setup-cpp@v1

      - name: Configure
        run: ./configure --prefix=$GITHUB_WORKSPACE/build

      - name: Build
        run: make -j $(nproc)

      - name: Test
        run: make check

      - name: Package
        run: make package

      - name: Upload package to the repository
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: build/package
